# Generated by Django 4.1.3 on 2022-11-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
                ('discipline', models.TextField()),
                ('times', models.TextField()),
                ('teacher', models.TextField()),
            ],
        ),
    ]
